AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation Template: Create an S3 bucket and an EC2 instance.'

Resources:

  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: ninad-s3-bucket-ver1

  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-08a52ddb321b32a8c 
      KeyName: EC2_tutorial
      SecurityGroups:
        - Ref: MySecurityGroup
      Tags:
        - Key: Name
          Value: First_Instance

  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0

Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref MyS3Bucket

  EC2InstanceID:
    Description: ID of the EC2 instance
    Value: !Ref MyEC2Instance
